# Generated by Django 2.0.7 on 2018-08-01 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='College',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Cos_Sim',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('similarity', models.IntegerField(default=0)),
                ('college', models.ForeignKey(on_delete='cascade', to='QueAns.College')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pass_result', models.IntegerField()),
                ('extra_curriculum', models.IntegerField()),
                ('expensive', models.IntegerField()),
                ('dress', models.IntegerField()),
                ('strict', models.IntegerField()),
                ('science', models.IntegerField()),
                ('management', models.IntegerField()),
                ('college', models.ForeignKey(on_delete='cascade', related_name='review', to='QueAns.College')),
            ],
        ),
    ]
