# Generated by Django 2.0.7 on 2018-08-02 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QueAns', '0002_review_variable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='variable',
            field=models.FloatField(default=0.0),
        ),
    ]
