# Generated by Django 2.0.7 on 2018-08-03 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QueAns', '0003_auto_20180802_0926'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='website',
            field=models.URLField(blank=True),
        ),
    ]
