# Generated by Django 2.0.7 on 2018-08-01 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QueAns', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='variable',
            field=models.IntegerField(default=0),
        ),
    ]
